---
abstract: 'Number 2 word conversion in POL.'
author:
  - 'Henrik Steffen <cpan@topconcepts.de>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-POL-Numbers
requires:
  Carp: 0
  Perl6::Export::Attrs: 0
  if: 0
  perl: v5.10.1
  strict: 0
  utf8: 0
  vars: 0
  warnings: 0
version: 0.135
